### ISSUE TITLE
dev override for scraper development

### ISSUE THREAD

**Issue by rhiaro** [OpenDataServices/oroi-deploy#1]
I want to add something like:

```
  memorious-worker:
    volumes:
      - "../oroi-scrape/oroi-scrape/scrapers:/oroi-scrape/scrapers"
      - "../oroi-scrape/oroi-scrape/config:/oroi-scrape/config"
    environment:
      MEMORIOUS_DEBUG: 'true'
```

to the dev override compose file, so I can work on scrapers and run them without having to rebuild any docker containers. But it didn't work! Neither the volumes nor the debug variable.
